{% set name = "aiosqlite" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e92961ae9e606b43b05e29b129e346b29e400fcbd63e3c0c564d89230257645

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - aiosqlite

about:
  home: https://github.com/jreese/aiosqlite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio bridge to the standard sqlite3 module
  description: |
    AsyncIO bridge to the standard sqlite3 module for Python 3.5+.
  dev_url: https://github.com/jreese/aiosqlite

extra:
  recipe-maintainers:
    - carlodri
