{% set name = "aiosqlite" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: faa843ef5fb08bafe9a9b3859012d3d9d6f77ce3637899de20606b7fc39aa213

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=2,<4
    - typing-extensions >=3.7.2
  run:
    - python >=3.6
    - typing-extensions >=3.7.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - aiosqlite

about:
  home: https://github.com/omnilib/aiosqlite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio bridge to the standard sqlite3 module
  description: |
    AsyncIO bridge to the standard sqlite3 module for Python 3.5+.
  dev_url: https://github.com/omnilib/aiosqlite

extra:
  recipe-maintainers:
    - carlodri
