{% set name = "aiosqlite" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad84fbd7516ca7065d799504fc41d6845c938e5306d1b7dd960caaeda12e22a9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - aiosqlite


about:
  home: https://github.com/jreese/aiosqlite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'asyncio bridge to the standard sqlite3 module'
  description: |
    AsyncIO bridge to the standard sqlite3 module for Python 3.5+.
  dev_url: https://github.com/jreese/aiosqlite

extra:
  recipe-maintainers:
    - carlodri
