travis:
  secure:
    BINSTAR_TOKEN: jcDKmLFv373pFrQZHaeBLDNTNll1V5WeTtr/DrSTqgqZnSjgjCfxK5vExeg2QsvzZXr4D4U0oACndIgW70jSLAnCeTFztVv6u0eax0Frn9MIlWJgJSQxH+U6CmkDokY7ScNsJJGosWuOKcc4vXcCZAuz5/jlCHyvQtOlhKVTSKQi4EWBQbrGL7dlzwvnQKtHvHdvISEzooEmdVjiL8uBc/TFtM3NRD2UHmF4kRc/Snm11u0rJVf95ZOhOq7XPXUrBSWDRSPgtQKBW8uNES1TN8oAa+8rRv7FMVLrBH3Zm5G6A0+1HxME7g/6aHtkA9UnPQcqiNdKt/yHVxcH01B/Ex9ytzzG+YmQNyYr6aYKNCzWqqdFKM1+naciQCWSzB57c4Q9iYF4BStqItaezVTXTLpVsTQct0WA3Vyg3chBYxWfhCdNrlfBgAIsJpevYT0xpVXBSzu4WprMNqxCpE4yf7B+/bNIJXjuYTPSvVcHGq36Uav6FHDgQh0A3IYfWS704VLPc4R3r63GFq5a4Z6QkvGb1ZOxeevoiIsnVScQRX/X/bcUtY5kh2QYA+hTwJgDZM0akXRf7aYK6desQSeSFDMWkKqwqcGasvg56yADE486NWi69a7ReGkkdMKKC0jyit/Esg4kV350AQV4vMEdFB1PCJsrR5tg4oIpXQ09K74=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
